# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: 2.1

jobs:
  test:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - run: &checkout_upstream
          name: Checkout upstream
          command: |
            git remote add upstream https://github.com/mozilla-services/mozilla-pipeline-schemas.git
            git fetch --all
      - setup_remote_docker:
          docker_layer_caching: true
          # `default` is recommended by CircleCI: https://discuss.circleci.com/t/remote-docker-image-deprecations-and-eol-for-2024/50176#what-do-i-need-to-do-2
          version: default
      - run:
          name: Build Docker image
          command: docker build --pull -t mps .
      - run:
          name: Test Code
          command: docker run mps
      - run:
          name: Verify that all generated schemas are committed
          command: docker run -w /app mps scripts/assert-consistent-schemas
      - run:
          name: Verify set version in telemetry namespace is correct
          command: docker run -w /app mps scripts/assert-telemetry-version
      - run:
          name: Generate diff artifacts for bigquery
          command: |
            # compare a branch against the main branch, or against the previous
            # commit if we're already on the main branch
            base=upstream/main
            if [[ "$CIRCLE_BRANCH" == "main" ]]; then
              base=HEAD~1
            fi
            docker run --name mps -w /app mps \
              mps bigquery diff --base-ref "$base"
            docker cp mps:/app/integration /tmp/integration
      - persist_to_workspace:
          root: /tmp
          paths:
            - integration
  post-artifacts:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run: npm i circle-github-bot
      - run: .circleci/post-artifact.js
      - store_artifacts:
          path: /tmp/integration
          destination: /app/integration

workflows:
    version: 2
    build:
      jobs:
        - test
        - post-artifacts:
            requires:
              - test
