# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: 2.1

jobs:
  test:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - run: &checkout_upstream
          name: Checkout upstream
          command: |
            git remote add upstream git@github.com:mozilla-services/mozilla-pipeline-schemas.git
            git fetch --all
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t mps .
      - run:
          name: Test Code
          command: docker run mps
      - run:
          name: Verify that all generated schemas are committed
          command: docker run -w /app mps scripts/assert-consistent-schemas
      - run:
          name: Verify set version in telemetry namespace is correct
          command: docker run -w /app mps scripts/assert-telemetry-version
      - run:
          name: Generate diff artifacts for bigquery
          command: |
            docker run --name mps -w /app mps \
              mps bigquery diff --base-ref upstream/master
            docker cp mps:/app/integration /tmp/integration
      - persist_to_workspace:
          root: /tmp
          paths:
            - integration
  post-artifacts:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run: npm i circle-github-bot
      - run: .circleci/post-artifact.js
      - store_artifacts:
          path: /tmp/test-reports
          destination: /app/test-reports

workflows:
    version: 2
    build:
      jobs:
        - test
        - integrate:
            filters:
              branches:
                # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
                ignore: /pull\/[0-9]+/
        - post-artifacts:
            requires:
              - test
            filters:
              branches:
                # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
                ignore: /pull\/[0-9]+/
